### PR TITLE
Add teacher can edit and delete activities from grove playlist

### PR DESCRIPTION
**Pull request by erinnachen**

### CODE REVIEW

**Comment by pindell-matt** [comment]
I know `Playlist Activity Policy` inherits from the `Student Management Policy` - do we want to make any adjustments for that?

**Comment by jedschneider** [comment]
@pindell-matt @erinnachen I think we leave the policy as is now while matt works on it. its likely it should be more restrictive than it is right now. like a normal teacher should not be able to view a student in another grove, unless they have admin privileges, I'd think.. Matt and I went over that yesterday and he has a good idea of where I'm going with that.

**Comment by jedschneider** [comment]
otherwise, GTM!

**Comment by NickyBobby** [comment]
Looks good to me too!  👍

**Pull request merged**
