### PR TITLE
View templating

### PR DESCRIPTION
**Pull request by brianrip**
Add basic bootstrap styling to existing views.

### CODE REVIEW

**Comment by jedschneider** [comment]
anything holding this up? I'm not certain it will be easy to merge since theres lots of work in the same views in other PR's. But, I'll leave that to the requseter to figure out.

**Comment by brianrip** [comment]
I will merge master to my branch and make updates.

**Comment by brianrip** [comment]
@jedschneider Updated with basic bootstrap style and imported google font. Merge if you approve

**Comment by brianrip** [comment]
@NickyBobby @erinnachen Is there a reason to hold this up?

**Comment by NickyBobby** [comment]
@brianrip I'll take a look at the code now

**Comment by NickyBobby** [comment]
This all looks GTM to me! 👍 💯

**Pull request merged**
